# Generated by Django 2.2.17 on 2020-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(blank=True, default='thePOST-default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
