# Generated by Django 2.2.17 on 2020-12-13 17:29

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201213_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(blank=True, default='thePOST-default.jpg', null=True, upload_to=blog.models.get_filename),
        ),
    ]
