# Generated by Django 2.2.17 on 2021-01-02 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, help_text='Add a blog title or headline to go beneath your name', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=userprofile.models.get_filename)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=userprofile.models.get_filename)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('website', models.URLField(blank=True, help_text='You can add a link to your personal website', null=True)),
                ('twitter', models.CharField(blank=True, max_length=16, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('following', models.ManyToManyField(related_name='followers', through='userprofile.Follower', to='userprofile.Profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='follower',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='userprofile.Profile'),
        ),
        migrations.AddField(
            model_name='follower',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='userprofile.Profile'),
        ),
    ]
