# Generated by Django 2.2.17 on 2020-12-28 15:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201224_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_title',
            field=models.CharField(blank=True, help_text='You can give your page a title to go under your name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_filename),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
