# Generated by Django 2.2.17 on 2020-12-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='user.Profile'),
        ),
    ]
